/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminComplaintsRouteImport } from './routes/admin.complaints'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminProcessingRouteImport } from './routes/admin.processing'
import { Route as AdminProfileRouteImport } from './routes/admin.profile'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminScheduleRouteImport } from './routes/admin.schedule'
import { Route as AdminServicesRouteImport } from './routes/admin.services'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppAddressesRouteImport } from './routes/app.addresses'
import { Route as AppHistoryRouteImport } from './routes/app.history'
import { Route as AppNewRouteImport } from './routes/app.new'
import { Route as AppPreferencesRouteImport } from './routes/app.preferences'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AdminLiveIdRouteImport } from './routes/admin.live.$id'
import { Route as AdminOrdersIndexRouteImport } from './routes/admin.orders.index'
import { Route as AdminOrdersIdRouteImport } from './routes/admin.orders.$id'
import { Route as AppOrdersIndexRouteImport } from './routes/app.orders.index'
import { Route as AppOrdersIdRouteImport } from './routes/app.orders.$id'
import { Route as AppPayIdRouteImport } from './routes/app.pay.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminComplaintsRoute = AdminComplaintsRouteImport.update({
  id: '/complaints',
  path: '/complaints',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProcessingRoute = AdminProcessingRouteImport.update({
  id: '/processing',
  path: '/processing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminScheduleRoute = AdminScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AdminRoute,
} as any)
const AdminServicesRoute = AdminServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AdminRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAddressesRoute = AppAddressesRouteImport.update({
  id: '/addresses',
  path: '/addresses',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppNewRoute = AppNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppRoute,
} as any)
const AppPreferencesRoute = AppPreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AdminLiveIdRoute = AdminLiveIdRouteImport.update({
  id: '/live/$id',
  path: '/live/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersIndexRoute = AdminOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersIdRoute = AdminOrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AppOrdersIndexRoute = AppOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersIdRoute = AppOrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppPayIdRoute = AppPayIdRouteImport.update({
  id: '/pay/$id',
  path: '/pay/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/admin/complaints': typeof AdminComplaintsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/processing': typeof AdminProcessingRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/schedule': typeof AdminScheduleRoute
  '/admin/services': typeof AdminServicesRoute
  '/app/addresses': typeof AppAddressesRoute
  '/app/history': typeof AppHistoryRoute
  '/app/new': typeof AppNewRoute
  '/app/preferences': typeof AppPreferencesRoute
  '/app/profile': typeof AppProfileRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/admin/live/$id': typeof AdminLiveIdRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/app/orders/$id': typeof AppOrdersIdRoute
  '/app/pay/$id': typeof AppPayIdRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/app/orders/': typeof AppOrdersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/complaints': typeof AdminComplaintsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/processing': typeof AdminProcessingRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/schedule': typeof AdminScheduleRoute
  '/admin/services': typeof AdminServicesRoute
  '/app/addresses': typeof AppAddressesRoute
  '/app/history': typeof AppHistoryRoute
  '/app/new': typeof AppNewRoute
  '/app/preferences': typeof AppPreferencesRoute
  '/app/profile': typeof AppProfileRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/admin/live/$id': typeof AdminLiveIdRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/app/orders/$id': typeof AppOrdersIdRoute
  '/app/pay/$id': typeof AppPayIdRoute
  '/admin/orders': typeof AdminOrdersIndexRoute
  '/app/orders': typeof AppOrdersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/admin/complaints': typeof AdminComplaintsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/processing': typeof AdminProcessingRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/schedule': typeof AdminScheduleRoute
  '/admin/services': typeof AdminServicesRoute
  '/app/addresses': typeof AppAddressesRoute
  '/app/history': typeof AppHistoryRoute
  '/app/new': typeof AppNewRoute
  '/app/preferences': typeof AppPreferencesRoute
  '/app/profile': typeof AppProfileRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/admin/live/$id': typeof AdminLiveIdRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/app/orders/$id': typeof AppOrdersIdRoute
  '/app/pay/$id': typeof AppPayIdRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/app/orders/': typeof AppOrdersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/admin/complaints'
    | '/admin/customers'
    | '/admin/payments'
    | '/admin/processing'
    | '/admin/profile'
    | '/admin/reports'
    | '/admin/schedule'
    | '/admin/services'
    | '/app/addresses'
    | '/app/history'
    | '/app/new'
    | '/app/preferences'
    | '/app/profile'
    | '/admin/'
    | '/app/'
    | '/admin/live/$id'
    | '/admin/orders/$id'
    | '/app/orders/$id'
    | '/app/pay/$id'
    | '/admin/orders/'
    | '/app/orders/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/complaints'
    | '/admin/customers'
    | '/admin/payments'
    | '/admin/processing'
    | '/admin/profile'
    | '/admin/reports'
    | '/admin/schedule'
    | '/admin/services'
    | '/app/addresses'
    | '/app/history'
    | '/app/new'
    | '/app/preferences'
    | '/app/profile'
    | '/admin'
    | '/app'
    | '/admin/live/$id'
    | '/admin/orders/$id'
    | '/app/orders/$id'
    | '/app/pay/$id'
    | '/admin/orders'
    | '/app/orders'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/admin/complaints'
    | '/admin/customers'
    | '/admin/payments'
    | '/admin/processing'
    | '/admin/profile'
    | '/admin/reports'
    | '/admin/schedule'
    | '/admin/services'
    | '/app/addresses'
    | '/app/history'
    | '/app/new'
    | '/app/preferences'
    | '/app/profile'
    | '/admin/'
    | '/app/'
    | '/admin/live/$id'
    | '/admin/orders/$id'
    | '/app/orders/$id'
    | '/app/pay/$id'
    | '/admin/orders/'
    | '/app/orders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/complaints': {
      id: '/admin/complaints'
      path: '/complaints'
      fullPath: '/admin/complaints'
      preLoaderRoute: typeof AdminComplaintsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/processing': {
      id: '/admin/processing'
      path: '/processing'
      fullPath: '/admin/processing'
      preLoaderRoute: typeof AdminProcessingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/schedule': {
      id: '/admin/schedule'
      path: '/schedule'
      fullPath: '/admin/schedule'
      preLoaderRoute: typeof AdminScheduleRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/services': {
      id: '/admin/services'
      path: '/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminServicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/addresses': {
      id: '/app/addresses'
      path: '/addresses'
      fullPath: '/app/addresses'
      preLoaderRoute: typeof AppAddressesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/history': {
      id: '/app/history'
      path: '/history'
      fullPath: '/app/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/new': {
      id: '/app/new'
      path: '/new'
      fullPath: '/app/new'
      preLoaderRoute: typeof AppNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/preferences': {
      id: '/app/preferences'
      path: '/preferences'
      fullPath: '/app/preferences'
      preLoaderRoute: typeof AppPreferencesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/live/$id': {
      id: '/admin/live/$id'
      path: '/live/$id'
      fullPath: '/admin/live/$id'
      preLoaderRoute: typeof AdminLiveIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders/': {
      id: '/admin/orders/'
      path: '/orders'
      fullPath: '/admin/orders/'
      preLoaderRoute: typeof AdminOrdersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders/$id': {
      id: '/admin/orders/$id'
      path: '/orders/$id'
      fullPath: '/admin/orders/$id'
      preLoaderRoute: typeof AdminOrdersIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/orders/': {
      id: '/app/orders/'
      path: '/orders'
      fullPath: '/app/orders/'
      preLoaderRoute: typeof AppOrdersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/orders/$id': {
      id: '/app/orders/$id'
      path: '/orders/$id'
      fullPath: '/app/orders/$id'
      preLoaderRoute: typeof AppOrdersIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pay/$id': {
      id: '/app/pay/$id'
      path: '/pay/$id'
      fullPath: '/app/pay/$id'
      preLoaderRoute: typeof AppPayIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AdminRouteChildren {
  AdminComplaintsRoute: typeof AdminComplaintsRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminProcessingRoute: typeof AdminProcessingRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminScheduleRoute: typeof AdminScheduleRoute
  AdminServicesRoute: typeof AdminServicesRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminLiveIdRoute: typeof AdminLiveIdRoute
  AdminOrdersIdRoute: typeof AdminOrdersIdRoute
  AdminOrdersIndexRoute: typeof AdminOrdersIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminComplaintsRoute: AdminComplaintsRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminProcessingRoute: AdminProcessingRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminScheduleRoute: AdminScheduleRoute,
  AdminServicesRoute: AdminServicesRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminLiveIdRoute: AdminLiveIdRoute,
  AdminOrdersIdRoute: AdminOrdersIdRoute,
  AdminOrdersIndexRoute: AdminOrdersIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppRouteChildren {
  AppAddressesRoute: typeof AppAddressesRoute
  AppHistoryRoute: typeof AppHistoryRoute
  AppNewRoute: typeof AppNewRoute
  AppPreferencesRoute: typeof AppPreferencesRoute
  AppProfileRoute: typeof AppProfileRoute
  AppIndexRoute: typeof AppIndexRoute
  AppOrdersIdRoute: typeof AppOrdersIdRoute
  AppPayIdRoute: typeof AppPayIdRoute
  AppOrdersIndexRoute: typeof AppOrdersIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAddressesRoute: AppAddressesRoute,
  AppHistoryRoute: AppHistoryRoute,
  AppNewRoute: AppNewRoute,
  AppPreferencesRoute: AppPreferencesRoute,
  AppProfileRoute: AppProfileRoute,
  AppIndexRoute: AppIndexRoute,
  AppOrdersIdRoute: AppOrdersIdRoute,
  AppPayIdRoute: AppPayIdRoute,
  AppOrdersIndexRoute: AppOrdersIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
